services:

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "8080:80"
      - "8443:443"
      - "127.0.0.1:2019:2019" # metrics at /metrics
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vpcbr
    environment:
      - DOMAIN_NAME=api.example.com
      - EMAIL=admin@example.com
      - CADDY_LOG_LEVEL=debug
    cap_add:
    - NET_BIND_SERVICE

  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    # ports:
      # - "8080:8080"
    volumes:
      - "./services/krakend/krakend.json:/etc/krakend/krakend.json"
    networks:
      - vpcbr
    depends_on:
      ping-service:
        condition: service_started
      consul:
        condition: service_started
    dns:
      - "192.0.2.10"  # Specify Consul's DNS IP here

  ping-service:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
     - "18080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  # Optionally specify restart policy
      resources:
        limits:
          cpus: "0.25"  # Limit CPU usage
          memory: "128M"  # Limit memory usage
        reservations:
          cpus: "0.1"  # Reserve CPU for the service
          memory: "64M"  # Reserve memory for the service
    environment:
      - CONSUL_HTTP_ADDR=http://192.0.2.10:8500
      - SERVICE_NAME=ping-service
      - SERVICE_PORT=18080
    networks:
      - vpcbr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/ping"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    labels:
      - "consul.service.name=ping-service"
      - "consul.service.checks=ping-service-health"
    depends_on:
      consul:
        condition: service_started

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: always
    ports:
      - '8500:8500'
      - '8600:53/tcp'
      - '8600:53/udp'
    volumes:
      - ./services/consul/consul-config:/consul/config
      - ./services/consul/consul.hcl:/consul/config/consul.hcl
    command: agent -server -bootstrap -ui -client=0.0.0.0 -config-dir=/consul/config
    networks:
      vpcbr:
        ipv4_address: 192.0.2.10
    # environment:
      # - CONSUL_BIND_INTERFACE=eth0

networks:
  vpcbr:
      driver: bridge
      ipam:
        config:
        - subnet: 192.0.2.0/24

volumes:
  caddy_data:
  caddy_config: