services:
  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    # command: ["sh", "-c", "ls -l /etc/krakend/ && krakend run -c /etc/krakend/krakend.json"]
    ports:
      - "8080:8080"
      - "8090:8090"  # Exposing the dashboard port
    volumes:
      - "./krakend.json:/etc/krakend/krakend.json"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ensure connectivity to the host
    networks:
      - web
    # depends_on:
    #   - consul

  # consul:
  #   image: hashicorp/consul:latest
  #   container_name: consul
  #   restart: always
  #   ports:
  #     - '8500:8500'
  #     - '8600:53/tcp'
  #     - '8600:53/udp'
  #   networks:
  #     vpcbr:
  #       ipv4_address: 192.0.2.10
  #   environment:
  #     CONSUL_LOCAL_CONFIG: |
  #       {
  #         "recursors": [
  #           "1.1.1.1",
  #           "9.9.9.9"
  #         ],
  #         "dns_config": {
  #           "recursor_strategy": "random"
  #         },
  #         "ports": {
  #           "dns": 53
  #         }
  #       }

  # debug:
  #   image: busybox
  #   container_name: kraken_conf_debug
  #   volumes:
  #     - "./krakend.json:/etc/krakend/krakend.json"
  #   command: ["sh", "-c", "cat /etc/krakend/krakend.json"]

networks:
#   vpcbr:
#       driver: bridge
#       ipam:
#         config:
#         - subnet: 192.0.2.0/24
  web:
    external: true
